name: Feature Request
description: 'No, I am not going to add 6K/etc notes to the engine, this will break noteskins.'
labels: [enhancement, status: pending triage]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **base** engine?
    validations:
      required: true
  - type: dropdown
    id: eyetest
    attributes:
      label: To test your sight, and reliability, please select the option of what should NOT be requested.
      options:
        - Proper credit that was forgotten
        - Thing that would not cause problems
        - Useful feature
        - Actual feedback
        - A good idea
        - Stage Editor and 6K+ support.
        - Better LUA mod support idea
        - Code optimization that would make the game faster. (You should make a Pull Request if this is your request, by the way.)
    validations:
      required: true
